### ISSUE TITLE
Naive Doubt regarding rule parser

### ISSUE THREAD

**Issue by harrydevnull** [rusticata/suricata#2]
how would I go about in validating the syntax/parsing rules that are send to suricata? 
i know suricata can be started in test mode and can be used to validate.
is it possible to make use this code base and build a rest sprinkling over it so that we could have the rules in proper fashion before reaching suricata. Apologies if this question is totally dumb.

**Comment by chifflier** [comment]
Hi,
This is a working copy of the suricata code, not the real project.
Please use the official Suricata support to get help: https://suricata-ids.org/support/
